version: 2

jobs:
  build-job:
    machine:
      image: windows-server-2019-vs2019:stable
    shell: powershell.exe
    resource_class: windows.medium
    steps:
      - checkout
      - run:
          name: Resolve dependency
          command: nuget restore
      - run:
          name: Build with MSBuild
          command: msbuild -p:Configuration=release -p:DeployOnBuild=true -p:WebPublishMethod=Package -p:PackageAsSingleFile=true -p:PackageLocation=HelloMVC.zip
      - store_artifacts:
          # This Zip file is a genuine Web Package and can be imported to IIS with Web Deploy, for example
          path: HelloMVC/HelloMVC.zip
      - persist_to_workspace:
          root: ./
          paths:
            - .
          # CD steps within this job or in a separate Docker-base job using this workspace

workflows:
  version: 2
  build-workflow:
    jobs:
      - build-job
